Repository Rust-Data-Science/ulist, pull requests merged in 2022-06, with the labels that each got.

#191 update dev guide.
  Dockerfile
  README.rst
  develop.rst
Labels: documentation

#193 style: cargo clippy for rust CI
  .github/workflows/main.yml
  ulist/src/base.rs
  ulist/src/boolean.rs
  ulist/src/control_flow.rs
  ulist/src/floatings/float64.rs
  ulist/src/integers/int32.rs
  ulist/src/integers/int64.rs
  ulist/src/io.rs
  ulist/src/numerical.rs
  ulist/src/string.rs
Labels: code quality

#186 Wip na behaviors
  .github/workflows/main.yml
  tests/run.sh
  tests/test_base.py
  tests/test_boolean.py
  tests/test_exceptions.py
  tests/test_numerical.py
  tests/test_string.py
  ulist/python/ulist/constructor.py
  ulist/python/ulist/core.py
  ulist/python/ulist/ulist.pyi
  ulist/src/base.rs
  ulist/src/boolean.rs
  ulist/src/floatings/float32.rs
  ulist/src/floatings/float64.rs
  ulist/src/integers/int32.rs
  ulist/src/integers/int64.rs
  ulist/src/numerical.rs
  ulist/src/string.rs
Labels: enhancement, design

#199 update ver.
  README.rst
  docs/conf.py
  ulist/Cargo.toml
  ulist/python/ulist/__init__.py
Labels: documentation
