Repository Rust-Data-Science/ulist, pull requests merged in 2022-05, with the labels that each got.

#160 Wip missing values
  docs/conf.py
  tests/test_base.py
  tests/test_boolean.py
  tests/test_constructors.py
  tests/test_control_flow.py
  tests/test_index.py
  tests/test_numerical.py
  tests/test_string.py
  ulist/Cargo.toml
  ulist/python/ulist/__init__.py
  ulist/python/ulist/constructor.py
  ulist/python/ulist/core.py
  ulist/python/ulist/typedef.py
  ulist/python/ulist/ulist.pyi
  ulist/python/ulist/utils.py
  ulist/src/base.rs
  ulist/src/boolean.rs
  ulist/src/control_flow.rs
  ulist/src/floatings/float32.rs
  ulist/src/floatings/float64.rs
  ulist/src/integers/int32.rs
  ulist/src/integers/int64.rs
  ulist/src/integers/mod.rs
  ulist/src/non_float.rs
  ulist/src/numerical.rs
  ulist/src/string.rs
Labels: enhancement

#170 A half done `read_csv` func
  ulist/python/ulist/__init__.py
  ulist/python/ulist/io.py
  ulist/python/ulist/ulist.pyi
  ulist/src/io.rs
  ulist/src/lib.rs
Labels: io

#173 fix-doc-build
  .github/workflows/sphinx.yml
  README.rst
Labels: bug, documentation

#174 fix py lib versions in .txt files
  .github/workflows/benchmark.yml
  .github/workflows/coverage.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/sphinx.yml
  requirements/bench.txt
  requirements/common.txt
  requirements/cov.txt
  requirements/dev.txt
  requirements/doc.txt
Labels: compatibility

#180 fix(base): fix `index out of range` when using iterator
  ulist/src/base.rs
  ulist/src/boolean.rs
  ulist/src/control_flow.rs
  ulist/src/floatings/float32.rs
  ulist/src/floatings/float64.rs
  ulist/src/integers/int32.rs
  ulist/src/integers/int64.rs
  ulist/src/string.rs
Labels: code quality

#185 refactor: using pyerr instead of panic
  ulist/src/base.rs
  ulist/src/boolean.rs
  ulist/src/control_flow.rs
  ulist/src/floatings/float32.rs
  ulist/src/floatings/float64.rs
  ulist/src/integers/int32.rs
  ulist/src/integers/int64.rs
  ulist/src/numerical.rs
  ulist/src/string.rs
Labels: code quality
